Project/eCommerce/eCommerce/Controllers/CitiesController.cs
using eCommerce.Data;
using eCommerce.Data.Services;
using eCommerce.Data.Static;
using eCommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eCommerce.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CitiesController : Controller
    {
        private readonly ICitiesService _service;

        public CitiesController(ICitiesService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allCities = await _service.GetAllAsync();
            return View(allCities);
        }
        //GET: producers/details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var cityDetails = await _service.GetByIdAsync(id);
            if (cityDetails == null) return View("NotFound");
            return View(cityDetails);
        }

        //GET: producers/create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ProfilePicture,FullName,Bio")] City city)
        {
            try
            {
                await _service.AddAsync(city);
                await _service.SaveChangesAsync();
                TempData["SuccessMessage"] = "Added a new City";//Đặt TempData
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(city);
            }

        }

        //GET: producers/edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");
            return View(producerDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProfilePicture,FullName,Bio")] City city)
        {
            try
            {
                await _service.UpdateAsync(id, city);
                await _service.SaveChangesAsync();
                TempData["SuccessMessage"] = "Successful edited your city";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(city);
            }
        }

        //GET: cities/delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var cityDetails = await _service.GetByIdAsync(id);
            if (cityDetails == null) return View("NotFound");
            return View(cityDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cityDetails = await _service.GetByIdAsync(id);
            if (cityDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);            
            await _service.SaveChangesAsync();
            TempData["SuccessMessage"] = "Deleted a City Successful";
            return RedirectToAction(nameof(Index));
        }
    }
}

Project/eCommerce/eCommerce/Controllers/OrdersController.cs
using eCommerce.Data.Cart;
using eCommerce.Data.Services;
using eCommerce.Data.ViewModels;
using eCommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace eCommerce.Controllers
{
    
    public class OrdersController : Controller
    {
        private readonly IProductsService _productService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;

        public OrdersController(IProductsService productService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _productService = productService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // Lấy UserId của người dùng hiện tại
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            // Sử dụng dịch vụ hoặc truy vấn để lấy danh sách đơn hàng của người dùng
            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);

            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(response);
        }

        [AllowAnonymous]
        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _productService.GetProductByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        [AllowAnonymous]
        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _productService.GetProductByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        [Authorize]
        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // Lấy UserId của người dùng hiện tại
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email); // Lấy địa chỉ email của người dùng hiện tại

            // Tạo đơn hàng với thông tin của người dùng hiện tại
            var order = new Order
            {
                Email = userEmailAddress,
                UserId = userId,
                OrderItems = items.Select(item => new OrderItem
                {
                    Amount = item.Amount,
                    Price = item.Product.Price,
                    ProductId = item.Product.Id
                }).ToList()
            };

            // Lưu đơn hàng vào Cơ sở dữ liệu    
            await _ordersService.AddOrderAsync(order);

            // Xóa giỏ hàng sau khi thanh toán
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteOrder(int id)
        {
            var order = await _ordersService.GetOrderByIdAsync(id);

            if (order == null)
            {
                return NotFound();
            }

            await _ordersService.DeleteAsync(id);

            // Cập nhật lại danh sách đơn hàng sau khi xóa
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var updatedOrders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);

            return View("Index", updatedOrders);
        }

    }
}

Project/eCommerce/eCommerce/Controllers/ProductsController.cs
using eCommerce.Data;
using eCommerce.Data.Enum;
using eCommerce.Data.Services;
using eCommerce.Data.Static;
using eCommerce.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace eCommerce.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ProductsController : Controller
    {

        private readonly IProductsService _service;

        public ProductsController(IProductsService service)
        {
            _service = service;
        }

        [AllowAnonymous] //chỉ định 1 action hoặc controller có thể truy cập mà không cần xác thực (đăng nhập)
        public async Task<IActionResult> Index(ProductCategory? category)
        {
            var allProducts = !category.HasValue
            ? await _service.GetAllAsync(n => n.Store)
            : await _service.GetProductsByCategoryAsync(category.Value);

            ViewBag.SelectedCategory = category; // Pass the selected category to the view
            ViewBag.Categories = await _service.GetDistinctCategoriesAsync(); // For dropdown

            return View(allProducts);
        }
        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var allProducts = await _service.GetAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allProducts
                    .Where(n => n.Name.StartsWith(searchString, StringComparison.CurrentCultureIgnoreCase))
                    .ToList();

                return View("Index", filteredResult);
            }

            return View("Index", allProducts);
        }
        //GET: Products/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var movieDetail = await _service.GetProductByIdAsync(id);
            return View(movieDetail);
        }

        //GET: Movies/Create
        public async Task<IActionResult> Create()
        {
            var productDropdownsData = await _service.GetNewProductDropdownsValues();

            ViewBag.Stores = new SelectList(productDropdownsData.Stores, "Id", "Name");
            ViewBag.Cites = new SelectList(productDropdownsData.Cities, "Id", "FullName");
            ViewBag.Companies = new SelectList(productDropdownsData.Companies, "Id", "FullName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewProductVM product)
        {
            if (!ModelState.IsValid)
            {
                var productDropdownsData = await _service.GetNewProductDropdownsValues();

                ViewBag.Stores = new SelectList(productDropdownsData.Stores, "Id", "Name");
                ViewBag.Cities = new SelectList(productDropdownsData.Cities, "Id", "FullName");
                ViewBag.Companies = new SelectList(productDropdownsData.Companies, "Id", "FullName");

                return View(product);
            }


            await _service.AddNewProductAsync(product);
            return RedirectToAction(nameof(Index));
        }


        //GET: Movies/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var productDetails = await _service.GetProductByIdAsync(id);
            if (productDetails == null) return View("NotFound");

            var response = new NewProductVM()
            {
                Id = productDetails.Id,
                Name = productDetails.Name,
                Description = productDetails.Description,
                Price = productDetails.Price,
                StartDate = productDetails.StartDay,
                EndDate = productDetails.EndDay,
                ImageURL = productDetails.ImageURL,
                ProductCategory = productDetails.ProductCategory,
                StoreId = productDetails.StoreId,
                CityId = productDetails.CityId,
                CompanyIds = productDetails.Company_Products.Select(n => n.CompanyId).ToList(),
            };

            var productDropdownsData = await _service.GetNewProductDropdownsValues();
            ViewBag.Stores = new SelectList(productDropdownsData.Stores, "Id", "Name");
            ViewBag.Cities = new SelectList(productDropdownsData.Cities, "Id", "FullName");
            ViewBag.Companies = new SelectList(productDropdownsData.Companies, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewProductVM product)
        {
            if (id != product.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var productDropdownsData = await _service.GetNewProductDropdownsValues();

                ViewBag.Stores = new SelectList(productDropdownsData.Stores, "Id", "Name");
                ViewBag.Cities = new SelectList(productDropdownsData.Cities, "Id", "FullName");
                ViewBag.Companies = new SelectList(productDropdownsData.Companies, "Id", "FullName");

                return View(product);
            }

            await _service.UpdateProductAsync(product);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")] // Đảm bảo chỉ Admin có quyền xóa
        public async Task<IActionResult> Delete(int id)
        {
            var product = await _service.GetByIdAsync(id);

            if (product == null)
            {
                return NotFound();
            }

            await _service.DeleteAsync(id);

            return RedirectToAction("Index");
        }
    }
}

Project/eCommerce/eCommerce/Controllers/StoresController.cs
using eCommerce.Data;
using eCommerce.Data.Services;
using eCommerce.Data.Static;
using eCommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eCommerce.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class StoresController : Controller
    {

        private readonly IStoresService _service;

        public StoresController(IStoresService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allStores = await _service.GetAllAsync();
            return View(allStores);
        }
        //Get: Stores/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo,Name,Description")] Store store)
        {
            try
            {
                await _service.AddAsync(store);
                await _service.SaveChangesAsync();
                TempData["SuccessMessage"] = "Added a new Store"; // Đặt TempData sau khi thêm thành công
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {            
                return View(store);
            }
        }

        //Get: Stores/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var storeDetails = await _service.GetByIdAsync(id);
            if (storeDetails == null) return View("NotFound");
            return View(storeDetails);
        }

        //Get: Stores/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var storeDetails = await _service.GetByIdAsync(id);
            if (storeDetails == null) return View("NotFound");
            return View(storeDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Description")] Store store)
        {
            try
            { //if (!ModelState.IsValid) return View(store);
                await _service.UpdateAsync(id, store);
                await _service.SaveChangesAsync();
                TempData["SuccessMessage"] = "Edited a Store Successful";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex) {
                return View(store);
            }
            
        }

        //Get: Stores/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var storeDetails = await _service.GetByIdAsync(id);
            if (storeDetails == null) return View("NotFound");
            return View(storeDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var storeDetails = await _service.GetByIdAsync(id);
            if (storeDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            await _service.SaveChangesAsync();
            TempData["SuccessMessage"] = "Deleted a Store Successful";
            return RedirectToAction(nameof(Index));
        }
    }
}

Project/eCommerce/eCommerce/Views/Shared/NotFound.cshtml
<div class="row ">
	<div class="col-md-6 offset-3">
		<h1 class="text-info">You've reached the end of the Internet</h1>
		<hr />
		<a class="btn btn-outline-success" asp-controller="Products" asp-action="Index">Home Page</a>
	</div>	
</div>

Project/eCommerce/eCommerce/Views/Shared/_CreateItem.cshtml
@model string;

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position: fixed; right: 25px; bottom: 75px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
            <i class="bi bi-plus-circle"></i> Add New
        </a>
    </div>
}

Project/eCommerce/eCommerce/Views/Shared/_Identity.cshtml
@using Microsoft.AspNetCore.Identity;

@inject UserManager<ApplicationUser> UserManager;


@if (!User.Identity.IsAuthenticated)
{

    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>
    <span style="padding: 5px;"></span>

    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>
}
else
{

    @*User profile section*@
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown"
                aria-expanded="false">
            <i class="bi bi-person-badge"></i> Hello @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list"></i> Orders
                </a>
            </li>

            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                        <i class="bi bi-people"></i> Users
                    </a>
                </li>
            }
        </ul>
    </div>
    <span style="padding: 5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Log out
        </button>
    </form>
}

Project/eCommerce/eCommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shoes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/eCommerce.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Products" asp-action="Index">Shoes</a> 
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="navbar-nav flex-grow-1">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index"><i class="badge-info bi-bag"></i> Products</a>
                            <div class="dropdown">
                                <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="categoryDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @(ViewBag.SelectedCategory == null ? "All Categories" : ViewBag.SelectedCategory.ToString())
                                </button>
                                <div class="dropdown-menu" aria-labelledby="categoryDropdown">
                                    <a class="dropdown-item" asp-controller="Products" asp-action="Index">All Categories</a>
                                    @foreach (var category in ViewBag.Categories ?? Enumerable.Empty<string>())
                                    {
                                        <a class="dropdown-item" asp-controller="Products" asp-action="Index" asp-route-category="@category">@category</a>
                                    }
                                </div>
                            </div>
                        </li>
                        

                        @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown m1-auto">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Stores" asp-action="Index"> <i class="bi bi-shop"></i> Stores</a>
                                    <a class="dropdown-item" asp-controller="Companies" asp-action="Index"> <i class="bi bi-person-square"></i> Companies</a>
                                    <a class="dropdown-item" asp-controller="Cities" asp-action="Index"> <i class="bi bi-building"></i> Cities</a>
                                </div>
                            </li>
                        }
                        
                    </ul>

                    <form asp-controller="Products" asp-action="Filter" method="get">
                        <div class="input-group">
                            <input type="text" class="form-control" name="searchString" placeholder="Search...">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary" type="submit">Search</button>
                            </div>
                        </div>
                    </form>
                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>

                    <partial name="_Identity.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - eCommerce
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<script>
    $(document).ready(function () {
        $(".navbar-toggler").click(function () {
            $(".navbar-collapse").toggleClass("show");
        });

        $("#categoryDropdown").click(function () {
            $(".dropdown-menu").toggleClass("show");
        });

        $(".dropdown-item").click(function () {
            var selectedCategory = $(this).text();
            $("#categoryDropdown").text(selectedCategory);
            $(".dropdown-menu").removeClass("show");
        });
    });
</script>