Project/eCommerce/eCommerce/Models/Product.cs
using eCommerce.Data.Base;
using eCommerce.Data.Enum;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace eCommerce.Models
{
    public class Product : IEntityBase
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
		public string Description { get; set; }
		public double Price { get; set; }
		public string ImageURL { get; set; }
        public DateTime StartDay { get; set; }
        public DateTime EndDay { get; set; }
        public ProductCategory ProductCategory { get; set; }

        // Relationships
        public List<Company_Product> Company_Products { get; set; }

        // Store
        public int StoreId { get; set; }
        [ForeignKey("StoreId")]
        public Store Store { get; set; }

        // City
        public int CityId { get; set; }
        [ForeignKey("CityId")]
        public City City { get; set; }

    }
}

Project/eCommerce/eCommerce/Controllers/CitiesController.cs
using eCommerce.Data;
using eCommerce.Data.Services;
using eCommerce.Data.Static;
using eCommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eCommerce.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CitiesController : Controller
    {
        private readonly ICitiesService _service;

        public CitiesController(ICitiesService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allCities = await _service.GetAllAsync();
            return View(allCities);
        }
        //GET: producers/details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var cityDetails = await _service.GetByIdAsync(id);
            if (cityDetails == null) return View("NotFound");
            return View(cityDetails);
        }

        //GET: producers/create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ProfilePicture,FullName,Bio")] City city)
        {
            try
            {
                await _service.AddAsync(city);
                await _service.SaveChangesAsync();
                TempData["SuccessMessage"] = "Added a new City";//Đặt TempData
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(city);
            }

        }

        //GET: producers/edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");
            return View(producerDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProfilePicture,FullName,Bio")] City city)
        {
            try
            {
                await _service.UpdateAsync(id, city);
                await _service.SaveChangesAsync();
                TempData["SuccessMessage"] = "Successful edited your city";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(city);
            }
        }

        //GET: cities/delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var cityDetails = await _service.GetByIdAsync(id);
            if (cityDetails == null) return View("NotFound");
            return View(cityDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cityDetails = await _service.GetByIdAsync(id);
            if (cityDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);            
            await _service.SaveChangesAsync();
            TempData["SuccessMessage"] = "Deleted a City Successful";
            return RedirectToAction(nameof(Index));
        }
    }
}

Project/eCommerce/eCommerce/Controllers/CompaniesController.cs
using eCommerce.Data;
using eCommerce.Data.Services;
using eCommerce.Data.Static;
using eCommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;

namespace eCommerce.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CompaniesController : Controller
    {
        private readonly ICompaniesService _service;

        public CompaniesController(ICompaniesService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        //Get: Companies/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Create([Bind("FullName, ProfilePicture, Bio")]Company company)
        {
            try
            {
                await _service.AddAsync(company);
                await _service.SaveChangesAsync();
                TempData["SuccessMessage"] = "Added a new Company"; // Đặt TempData sau khi thêm thành công
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(company);
            }
        }

        // Get: Companies/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var companyDetails = await _service.GetByIdAsync(id);
            
            if(companyDetails == null) return View("Not found");

            return View(companyDetails);
        }

        //Get: Companies/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var companyDetails = await _service.GetByIdAsync(id);
            if (companyDetails == null) return View("Not found");
            return View(companyDetails);
        }

        [HttpPost]

        public async Task<IActionResult> Edit(int id, [Bind("Id, FullName, ProfilePicture, Bio")] Company company)
        {
            try
            {
                await _service.UpdateAsync(id, company);
                await _service.SaveChangesAsync();
                TempData["SuccessMessage"] = "Successful Edited Your Company"; // Đặt TempData sau khi thêm thành công
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(company);
            }
        }

        //Get: Companies/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var companyDetails = await _service.GetByIdAsync(id);
            if (companyDetails == null) return View("Not found");
            return View(companyDetails);
        }

        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var companyDetails = await _service.GetByIdAsync(id);
            if (companyDetails == null) return View("Not found");

            await _service.DeleteAsync(id);
            await _service.SaveChangesAsync();
            TempData["SuccessMessage"] = "Successful Deleted Your Company";
            return RedirectToAction(nameof(Index));
        }
    }
}

Project/eCommerce/eCommerce/Controllers/OrdersController.cs
using eCommerce.Data.Cart;
using eCommerce.Data.Services;
using eCommerce.Data.ViewModels;
using eCommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace eCommerce.Controllers
{
    
    public class OrdersController : Controller
    {
        private readonly IProductsService _productService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;

        public OrdersController(IProductsService productService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _productService = productService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // Lấy UserId của người dùng hiện tại
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            // Sử dụng dịch vụ hoặc truy vấn để lấy danh sách đơn hàng của người dùng
            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);

            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(response);
        }

        [AllowAnonymous]
        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _productService.GetProductByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        [AllowAnonymous]
        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _productService.GetProductByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        [Authorize]
        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // Lấy UserId của người dùng hiện tại
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email); // Lấy địa chỉ email của người dùng hiện tại

            // Tạo đơn hàng với thông tin của người dùng hiện tại
            var order = new Order
            {
                Email = userEmailAddress,
                UserId = userId,
                OrderItems = items.Select(item => new OrderItem
                {
                    Amount = item.Amount,
                    Price = item.Product.Price,
                    ProductId = item.Product.Id
                }).ToList()
            };

            // Lưu đơn hàng vào Cơ sở dữ liệu    
            await _ordersService.AddOrderAsync(order);

            // Xóa giỏ hàng sau khi thanh toán
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteOrder(int id)
        {
            var order = await _ordersService.GetOrderByIdAsync(id);

            if (order == null)
            {
                return NotFound();
            }

            await _ordersService.DeleteAsync(id);

            // Cập nhật lại danh sách đơn hàng sau khi xóa
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var updatedOrders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);

            return View("Index", updatedOrders);
        }

    }
}

Project/eCommerce/eCommerce/Controllers/StoresController.cs
using eCommerce.Data;
using eCommerce.Data.Services;
using eCommerce.Data.Static;
using eCommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eCommerce.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class StoresController : Controller
    {

        private readonly IStoresService _service;

        public StoresController(IStoresService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allStores = await _service.GetAllAsync();
            return View(allStores);
        }
        //Get: Stores/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo,Name,Description")] Store store)
        {
            try
            {
                await _service.AddAsync(store);
                await _service.SaveChangesAsync();
                TempData["SuccessMessage"] = "Added a new Store"; // Đặt TempData sau khi thêm thành công
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {            
                return View(store);
            }
        }

        //Get: Stores/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var storeDetails = await _service.GetByIdAsync(id);
            if (storeDetails == null) return View("NotFound");
            return View(storeDetails);
        }

        //Get: Stores/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var storeDetails = await _service.GetByIdAsync(id);
            if (storeDetails == null) return View("NotFound");
            return View(storeDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Description")] Store store)
        {
            try
            { //if (!ModelState.IsValid) return View(store);
                await _service.UpdateAsync(id, store);
                await _service.SaveChangesAsync();
                TempData["SuccessMessage"] = "Edited a Store Successful";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex) {
                return View(store);
            }
            
        }

        //Get: Stores/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var storeDetails = await _service.GetByIdAsync(id);
            if (storeDetails == null) return View("NotFound");
            return View(storeDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var storeDetails = await _service.GetByIdAsync(id);
            if (storeDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            await _service.SaveChangesAsync();
            TempData["SuccessMessage"] = "Deleted a Store Successful";
            return RedirectToAction(nameof(Index));
        }
    }
}

Project/eCommerce/eCommerce/Views/Products/Create.cshtml
@model NewProductVM;
@using eCommerce.Data;
@using eCommerce.Data.Enum;
@using eCommerce.Data.ViewModels;

@{
    ViewData["Title"] = "Create a new movie";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4 class="text-center">CREATE A NEW PRODUCT</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label">Product Name</label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="StartDate" class="control-label">Product Start Date</label>
                                <input asp-for="StartDate" type="date" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="EndDate" class="control-label">Product End Date</label>
                                <input asp-for="EndDate" type="date" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label">Price in $</label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageURL" class="control-label">Product Poster URL</label>
                                <input asp-for="ImageURL" class="form-control" />
                                <span asp-validation-for="ImageURL" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="StoreId" class="control-label">Select a Store</label>
                                <select asp-for="StoreId" class="form-control" asp-items="ViewBag.Stores"></select>
                                <span asp-validation-for="StoreId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ProductCategory" class="control-label">Select a Category</label>
                                <select asp-for="ProductCategory" class="form-control" asp-items="Html.GetEnumSelectList<ProductCategory>()"></select>
                                <span asp-validation-for="ProductCategory" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CityId" class="control-label">Select a City</label>
                                <select asp-for="CityId" class="form-control" asp-items="ViewBag.Cites"></select>
                                <span asp-validation-for="CityId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CompanyIds" class="control-label">Select a Company(s)</label>
                                <select asp-for="CompanyIds" class="form-control" asp-items="ViewBag.Companies" multiple></select>
                                <span asp-validation-for="CompanyIds" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label">Product Description</label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group d-flex justify-content-between"> 
                        <input type="submit" value="Create" class="btn btn-success" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

@section Scripts{
    <script>
        $("#ImageURL").on("change", function () {
            var output = document.getElementById("#ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}

Project/eCommerce/eCommerce/Views/Products/Details.cshtml
@model Product

@{
    ViewData["Title"] = "Product details";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-success">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImageURL" width="100%" alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>
                        <p class="card-text">
                            <b>Store: </b>
                            <a asp-controller="Stores" asp-action="Details" asp-route-id="@Model.StoreId">
                                @Model.Store.Name
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Company: </b>
                            <a asp-controller="Cities" asp-action="Details" asp-route-id="@Model.CityId">
                                @Model.City.FullName
                            </a>
                        </p>
                        <p class="card-text"><b>Category: </b>@Model.ProductCategory</p>
                        <p class="card-text"><b>Start Date: </b>@Model.StartDay.ToString("dd MMM yyyy")</p>
                        <p class="card-text"><b>End Date: </b>@Model.EndDay.ToString("dd MMM yyyy")</p>
                        <p class="card-text ">
                            <b>Status: </b>
                            @if (DateTime.Now >= Model.StartDay && DateTime.Now <= Model.EndDay)
                            {
                                <span class="badge bg-success text-white">AVAILABLE</span>
                            }
                            else if (DateTime.Now > Model.EndDay)
                            {
                                <span class="badge bg-danger text-white">OUT OF STOCK</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-white">UPCOMING</span>
                            }
                        </p>
                        <p class="card-text">
                            <b>Companies: </b>
                            <hr />
                            <div class="row">
                                @foreach (var actor in Model.Company_Products)
                                {
                                    <div class="column text-center">
                                        <img class="border-info rounded-circle" src="@actor.Company.ProfilePicture" style="max-width: 150px" />
                                        <br />
                                        <a asp-controller="Companies" asp-action="Details" asp-route-id="@actor.CompanyId">@actor.Company.FullName</a>
                                    </div>
                                }
                            </div>
                        </p>

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <div class="d-flex justify-content-between">
                                <a class="btn btn-outline-primary" asp-action="Index">
                                    Back to List
                                </a>
                                <a class="btn btn-success text-white @((DateTime.Now > Model.EndDay) ? "disabled" : "")"
                                   asp-controller="Orders"
                                   asp-action="AddItemToShoppingCart" asp-route-id="@Model.Id">
                                    <i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c"))
                                </a>
                            </div>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Project/eCommerce/eCommerce/Views/Products/Index.cshtml
@model IEnumerable<Product>

@{
    ViewData["Title"] = "List of Products";
}


<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-success">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                    }
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageURL" width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"><b>Store: </b>@item.Store?.Name</p>
                            <p class="card-text"><b>Category: </b>@item.ProductCategory</p>
                            <p class="card-text"><b>Start Date: </b>@item.StartDay.ToString("dd MMM yyyy")</p>
                            <p class="card-text"><b>End Date: </b>@item.EndDay.ToString("dd MMM yyyy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDay && DateTime.Now <= item.EndDay)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDay)
                                {
                                    <span class="badge bg-danger text-white">OUT OF STOCK</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer">
                            <p class="card-text">
                                <div class="d-flex justify-content-between align-items-center">
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <form asp-action="Delete" asp-route-id="@item.Id" method="post" onsubmit="return confirm('Are you sure you want to delete this product?');">
                                            <button type="submit" class="btn btn-danger btn-sm">
                                                <i class="bi bi-trash"></i> Delete
                                            </button>
                                        </form>
                                    }
                                    <div class="d-flex w-100 justify-content-around">
                                        <a class="btn btn-outline-primary btn-sm" asp-action="Details" asp-route-id="@item.Id">
                                            <i class="bi bi-eye-fill"></i> Show Details
                                        </a>
                                        <a class="btn btn-success btn-sm text-white @((DateTime.Now > item.EndDay) ? "disabled" : "")"
                                           asp-controller="Orders"
                                           asp-action="AddItemToShoppingCart"
                                           asp-route-id="@item.Id">
                                            <i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))
                                        </a>
                                    </div>
                                </div>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@await Html.PartialAsync("_CreateItem", "Products")